table FactVentes
	lineageTag: 8b141c6f-0a14-4c00-91da-d4e5e9b5e4c2

	column VenteID
		dataType: string
		isHidden
		lineageTag: e52e8998-95ee-42ec-9c3c-d36f2a825fce
		summarizeBy: none
		sourceColumn: VenteID

		annotation SummarizationSetBy = Automatic

	column DateVente
		dataType: dateTime
		formatString: Long Date
		lineageTag: eff953e6-a4de-4c36-9386-da40664e2c09
		summarizeBy: none
		sourceColumn: DateVente

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Canal
		dataType: string
		lineageTag: 75f35e4d-4160-48c2-932e-51e4678ca3cb
		summarizeBy: none
		sourceColumn: Canal

		annotation SummarizationSetBy = Automatic

	column StatutCommande
		dataType: string
		lineageTag: 0ff3d865-3e98-4785-8fa1-79a18bed5f90
		summarizeBy: none
		sourceColumn: StatutCommande

		annotation SummarizationSetBy = Automatic

	column IdProduit
		dataType: string
		isHidden
		lineageTag: 9f59c968-588c-41d8-b882-62b106164941
		summarizeBy: none
		sourceColumn: IdProduit

		annotation SummarizationSetBy = Automatic

	column Quantite
		dataType: int64
		formatString: 0
		lineageTag: d70c0b6f-6ee5-4bcf-b875-48644fd7909c
		summarizeBy: sum
		sourceColumn: Quantite

		annotation SummarizationSetBy = Automatic

	column TauxRemise
		dataType: int64
		formatString: 0
		lineageTag: c2b96367-4c14-489d-a037-1f40c542043d
		summarizeBy: none
		sourceColumn: TauxRemise

		annotation SummarizationSetBy = Automatic

	column MontantBrutTTC
		dataType: double
		formatString: 0
		lineageTag: 6bbf98a3-88b3-4afb-a6ce-7bfc3dc31f03
		summarizeBy: sum
		sourceColumn: MontantBrutTTC

		annotation SummarizationSetBy = Automatic

	column MontantNetTTC
		dataType: double
		lineageTag: cc5aebb9-9ae6-4a46-8f88-e29108be6e11
		summarizeBy: sum
		sourceColumn: MontantNetTTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CoutLigne
		dataType: double
		lineageTag: 0499597b-d0d2-4a91-9655-c6ca578caeed
		summarizeBy: none
		sourceColumn: CoutLigne

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IdMagasin
		dataType: string
		isHidden
		lineageTag: df6ca9f8-9d84-47bf-89e2-2281053d0203
		summarizeBy: none
		sourceColumn: IdMagasin

		annotation SummarizationSetBy = Automatic

	column IdVendeur
		dataType: string
		isHidden
		lineageTag: edfb5cf0-4f58-407b-8cee-9c9f3ef98198
		summarizeBy: none
		sourceColumn: IdVendeur

		annotation SummarizationSetBy = Automatic

	column IdClient
		dataType: string
		isHidden
		lineageTag: dfe73bec-97f8-4a06-86fd-4e52c47b507e
		summarizeBy: none
		sourceColumn: IdClient

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7a490a65-27e3-4756-b3a3-0854a2025f5f
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	partition FactVentes = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents(DossierData & "\ventes.csv"), [Delimiter = ";", Columns = 13, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Type de colonne changé" = Table.TransformColumnTypes(#"En-têtes promus", {{"VteID", type text}, {"DtVte", type date}, {"Canal", type text}, {"StatutCde", type text}, {"ProdID", type text}, {"Qt", Int64.Type}, {"TxRem", Int64.Type}, {"MttBrutTTC", Int64.Type}, {"MttTTcNet", type number}, {"CstLigne", type number}, {"MagID", type text}, {"VndID", type text}, {"CustNo", type text}}, "fr"),
				    #"Colonnes renommées" = Table.RenameColumns(#"Type de colonne changé",{{"VteID", "VenteID"}, {"DtVte", "DateVente"}, {"StatutCde", "StatutCommande"}, {"ProdID", "IdProduit"}, {"Qt", "Quantite"}, {"TxRem", "TauxRemise"}, {"MttBrutTTC", "MontantBrutTTC"}, {"MttTTcNet", "MontantNetTTC"}, {"CstLigne", "CoutLigne"}, {"MagID", "IdMagasin"}, {"VndID", "IdVendeur"}, {"CustNo", "IdClient"}}),
				    #"Type modifié" = Table.TransformColumnTypes(#"Colonnes renommées",{{"MontantBrutTTC", type number}}),
				    #"Personnalisée ajoutée" = Table.AddColumn(#"Type modifié", "DateKey", each Number.FromText(Date.ToText([DateVente], "yyyyMMdd"))),
				    #"Type modifié1" = Table.TransformColumnTypes(#"Personnalisée ajoutée",{{"DateKey", Int64.Type}}),
				    #"Majuscule à chaque mot" = Table.TransformColumns(#"Type modifié1",{{"StatutCommande", Text.Proper, type text}, {"Canal", Text.Proper, type text}}),
				    #"Espaces supprimés" = Table.TransformColumns(#"Majuscule à chaque mot",{{"StatutCommande", Text.Trim, type text}, {"Canal", Text.Trim, type text}})
				in
				    #"Espaces supprimés"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

