table calendrier
	lineageTag: c718e0c1-f602-4f6b-8ca9-492a25427020

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 510ae921-aa51-4575-a9e3-fa28b7636195
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 95edde51-5846-42b8-ac03-c9ae7cafd905
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Annee
		dataType: int64
		formatString: 0
		lineageTag: d4f7424c-10ae-4138-8274-9c6012c777f7
		summarizeBy: sum
		sourceColumn: Annee

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 26d2c2f5-4af5-4a2b-8e55-e97444202ed3
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column MoisNum
		dataType: int64
		formatString: 0
		lineageTag: 6fa23430-8bad-4fa7-9d1c-a4dbeaa4d57d
		summarizeBy: sum
		sourceColumn: MoisNum

		annotation SummarizationSetBy = Automatic

	column MoisLbl
		dataType: string
		lineageTag: 44f77a35-292c-4a56-8fc1-88001e095491
		summarizeBy: none
		sourceColumn: MoisLbl

		annotation SummarizationSetBy = Automatic

	column JourNum
		dataType: int64
		formatString: 0
		lineageTag: 09327af9-53e6-4f6f-90a9-999d02a2c2e4
		summarizeBy: sum
		sourceColumn: JourNum

		annotation SummarizationSetBy = Automatic

	column JourSemLbl
		dataType: string
		lineageTag: 065bcc9d-9f4d-4ad3-a9ff-2d4595ea7e75
		summarizeBy: none
		sourceColumn: JourSemLbl

		annotation SummarizationSetBy = Automatic

	column NumSem
		dataType: int64
		formatString: 0
		lineageTag: 310bb9ee-2c88-4dad-894e-48ce1b633d72
		summarizeBy: sum
		sourceColumn: NumSem

		annotation SummarizationSetBy = Automatic

	partition calendrier = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\dev\genai-powerbi-fabric\assets\data\brut\calendrier.csv"), [Delimiter = ";", Columns = 9, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Type de colonne changé" = Table.TransformColumnTypes(#"En-têtes promus", {{"DateKey", Int64.Type}, {"Date", type date}, {"Annee", Int64.Type}, {"Trimestre", type text}, {"MoisNum", Int64.Type}, {"MoisLbl", type text}, {"JourNum", Int64.Type}, {"JourSemLbl", type text}, {"NumSem", Int64.Type}}, "fr")
				in
				  #"Type de colonne changé"

	annotation PBI_ResultType = Table

